### ISSUE TITLE
Usage issue with ustd::map

### ISSUE THREAD

**Issue by merk** [muwerk/ustd#12]
I'm not very knowledgable with C++ and might be doing something wrong - a pointer in the right direction would be appreciated if that is the case. I'm using platformio on a feather m4 (with __FEATHER_M4__ define).

I'm trying to create a map of integers->integers, and I'm getting compile time errors:

```c++
ustd::map<uint8_t, uint8_t> ledMap = ustd::map<uint8_t, uint8_t>(LED_TOTAL, LED_TOTAL, 0);
ledMap[0] = 0;
```

```
src\animation.h:14:1: error: 'ledMap' does not name a type
   14 | ledMap[0] = 0;
      | ^~~~~~
```

**Comment by mo22** [comment]
the line `ledMap[0] = 0;` has to go in a function, like in your setup function.

```
ustd::map<uint8_t, uint8_t> ledMap = ustd::map<uint8_t, uint8_t>(LED_TOTAL, LED_TOTAL, 0);

setup() {
  ledMap[0] = 0;
}
```

**Comment by domschl** [comment]
@mo22 tx for the explanation. Closing.
