### ISSUE TITLE
Static initialization syntax & access

### ISSUE THREAD

**Issue by selkovjr** [muwerk/ustd#15]
In the example given for static allocation,

  `ustd::map<int, float> mayMap = ustd::map<int,float>(5, 5, 0, false);`
  
 what is meaning of items in parentheses? If they are pairs, they are odd-looking pairs.
 
 I tried the c++11 list intialization; it did not work. I tried to put my stuff in like so:
 ```
   const ustd::map<uint8_t, const uint16_t(*)[64]> sprite = ustd::map<uint8_t, const uint16_t(*)[64]>(
    7, &dial_face_7,
    8, &dial_face_8
  );
```
and it compiled, but I could not access the values. Find(7) returs -1. I wouldn't know what to do with a valid array position if it returned one. Trying keysArray, I got:

invalid initialization of reference of type 'const ustd::array<unsigned char>& (ustd::map<unsigned char, const unsigned int (*)[64]>::*&&)()' from expression of type '<unresolved overloaded function type>'

Is there a working example of static use?

**Comment by domschl** [comment]
The values are not for initializing the map, they are default sizes of the internal memory buffers used by `ustd::map`, see the [documentation](https://muwerk.github.io/ustd/docs/classustd_1_1map.html):

Constructor of `ustd::map` take a number of parameters that allow to configure (and restrict) the memory usage of the map:
```
map (unsigned int startSize=ARRAY_INIT_SIZE, unsigned int maxSize=ARRAY_MAX_SIZE, unsigned int incSize=ARRAY_INC_SIZE, bool shrink=true)
```
In your example, initially, memory for `5` elements is allocated, the maximum length of the map is restricted to `5`, no increments of the size (memory usage) of the map (`0`), and no shrinking (deallocation of memory) (`false`).

If you simply do not give any constructor-values, it will work as an automatically expanding map that allocates memory on demand.

**Comment by domschl** [comment]
Closing this. Please feel free to reopen or make a new issue if anything remains unclear.
