### ISSUE TITLE
Adding board nano_every

### ISSUE THREAD

**Issue by joshuisken** [muwerk/ustd#19]
Would like to use muserial on a nano_every board.
Any advice how to add this board to your platform?

**Comment by domschl** [comment]
From looking at the datasheet of [arduino_every](https://store.arduino.cc/products/arduino-nano-every?selectedStore=eu), I would guess that

```
#define __ATMEGA__
```

as platform define (before other `ustd` includes) should work just fine. (The nano-every has slightly less SRAM than the mega, but I don't think that will cause issues -- if is does, we can search for another solution)

**Comment by joshuisken** [comment]
I added code below (under a new #define) instead of #define __ATMEGA__ since compilation failed with #include "new.h"
```
#define KNOWN_PLATFORM 1
#define USTD_FEATURE_MEMORY 48640
#define USTD_FEATURE_EEPROM
#define __ARDUINO__ 1
```
This solved my problem.

**Comment by domschl** [comment]
Good.

Just one remark: 
```
#define USTD_FEATURE_MEMORY 6144
```
It is the amount of RAM (SRAM) that is described with that define. This doesn't matter at all, if no libraries are used that look for either this or the derived defines `USTD_FEATURE_MEM_*`. 
The USTD libraries themselves don't use those, but they are used by [`muwerk` scheduler](https://github.com/muwerk/muwerk).

So, when only using ustd_* libs, the value doesn't matter.
