### ISSUE TITLE
adding iterator and support for emplace

### ISSUE THREAD

**Issue by proddy** [muwerk/ustd#4]
First, thanks for these great libraries. I've been benchmarking a few techniques to address a memory heap problem I have an ESP8266. For example if I load 200 structs into an std::vector it uses 9400 bytes while your array.h uses only 7500 bytes of dynamic memory. I know 200 is high, but it was just for a test and performance is not critical. Anyway, very cool!

I was wondering whether you have, or had plans to extend the class to implement an iterator (for easier looping) or emplacing' so the element is constructed and added into the container without copying?

If not, I'll give it'll a go.....

**Comment by proddy** [comment]
I added an iterator a while back, didn't do a PR since I thought this repo was dormant. Anyway, the code (for queue as an example) if anyone is interested....

```C
template <typename T>
class queueIterator {
  public:
    queueIterator(T * values_ptr, uint8_t p)
        : values_ptr_{values_ptr}
        , position_{p} {
    }

    bool operator!=(const queueIterator<T> & other) const {
        return !(*this == other);
    }

    bool operator==(const queueIterator<T> & other) const {
        return position_ == other.position_;
    }

    queueIterator & operator++() {
        ++position_;
        return *this;
    }

    T & operator*() const {
        return *(values_ptr_ + position_);
    }

  private:
    T *     values_ptr_;
    uint8_t position_;
};
```

and to the main class add

```C
class queue {
....
    // iterators
    queueIterator<T> begin() {
        return queueIterator<T>(que_, quePtrFront_);
    }
    queueIterator<T> end() {
        return queueIterator<T>(que_, quePtrFront_ + size_);
    }

    queueIterator<const T> begin() const {
        return queueIterator<const T>(que_, quePtrFront_);
    }

    queueIterator<const T> end() const {
        return queueIterator<const T>(que_, quePtrFront_ + size_);
    }
}
```

**Comment by domschl** [comment]
Tx, I'll have a look at this soon!

**Comment by domschl** [comment]
I'm adding iterators with that helpful sample code (currently in branch feature/iterator), should be added soon. For some reason I had the impression it would add too much "weight" to add iterators, which proved wrong. So thanks for those really helpful samples!

**Comment by proddy** [comment]
no worries, i had iterators for the other containers too. basically the same

**Comment by domschl** [comment]
I made a small change to you queue suggestion to account for queue being a ring-buffer, so the position pointer wraps around:

* https://github.com/muwerk/ustd/blob/784310f51c98e9bdccf2a533f93df30b6c83b142/ustd_queue.h#L28
* https://github.com/muwerk/ustd/blob/784310f51c98e9bdccf2a533f93df30b6c83b142/ustd_queue.h#L156

A new version 0.6.0 is being released with iterator support. Thank you for your help!
